<?xml version="1.0" encoding="utf-8"?><Database Name="DataWarehouse" Class="DataWarehouseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVER;Initial Catalog=DataWarehouse;Integrated Security=True" SettingsObjectName="W3CLogFileParser.Properties.Settings" SettingsPropertyName="DataWarehouseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Logs.IisRequest" Member="IisRequests">
    <Type Name="IisRequest">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ServerName" Type="System.String" DbType="VarChar(63)" CanBeNull="true" />
      <Column Name="ServerIP" Type="System.Data.Linq.Binary" DbType="VarBinary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ServerPort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UriStem" Type="System.String" DbType="VarChar(2100)" CanBeNull="true" />
      <Column Name="UriQuery" Type="System.String" DbType="VarChar(2100)" CanBeNull="true" />
      <Column Name="TimeTakenInMilliseconds" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ProtocolStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ProtocolSubstatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ProtocolVersion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ClientIP" Type="System.Data.Linq.Binary" DbType="VarBinary(16)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserAgent" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="Referrer" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Cookie" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Win32Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Host" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="BytesSent" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BytesReceived" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>